version: '3'
networks:
  q_network:
    driver: bridge
    ipam:
      config:
        - subnet: "172.32.0.0/24"

services:
  app:
    build:
      context: ../../images/govready-q
      dockerfile: Dockerfile
      args:
        - VERSION=${VERSION}
        - GIT_URL=${GIT_URL}
        - BUILD_FILE_BRANDING=${BUILD_FILE_BRANDING-}
        - DB_ENGINE=${DB_ENGINE-}
        - GR_PDF_GENERATOR=${GR_PDF_GENERATOR-}
        - GR_IMG_GENERATOR=${GR_IMG_GENERATOR-}
    command: /bin/bash -c docker_exec_prod.sh
    environment:
      - DATABASE_CONNECTION_STRING=${DATABASE_CONNECTION_STRING-}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS-}
      - HOST_ADDRESS=${HOST_ADDRESS-}
      - HOST_PORT_HTTPS=${HOST_PORT_HTTPS-}
      - APP_DOCKER_PORT=${APP_DOCKER_PORT-}
      - SECRET_KEY=${SECRET_KEY-}
      - DEBUG=${DEBUG-}
      - ADMINS=${ADMINS-[]}
      - HEALTH_CHECK_GOVREADY_Q=${HEALTH_CHECK_GOVREADY_Q}
      - EMAIL_HOST=${EMAIL_HOST-}
      - EMAIL_PORT=${EMAIL_PORT-}
      - EMAIL_PW=${EMAIL_PW-}
      - EMAIL_DOMAIN=${EMAIL_DOMAIN-}
      - MAILGUN_API_KEY=${MAILGUN_API_KEY-}
      - BRANDING=${BRANDING-}
      - PROXY_AUTHENTICATION_USER_HEADER=${PROXY_AUTHENTICATION_USER_HEADER-}
      - PROXY_AUTHENTICATION_EMAIL_HEADER=${PROXY_AUTHENTICATION_EMAIL_HEADER-}
      - GR_PDF_GENERATOR=${GR_PDF_GENERATOR-}
      - GR_IMG_GENERATOR=${GR_IMG_GENERATOR-}
      - OKTA=${OKTA-}
    volumes:
      - ${MOUNT_FOLDER}/govready-q/logs:/var/log
      - ${MOUNT_FOLDER}/govready-q/data:/data
    ports:
      - "${APP_DOCKER_PORT-8000}:8000"
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: curl --fail -s $$HEALTH_CHECK_GOVREADY_Q || exit 1
      interval: 10s
      timeout: 5s
      retries: 15
    networks:
      - q_network

  email-notifications:
    build:
      context: ../../images/govready-q
      dockerfile: Dockerfile
      args:
        - VERSION=${VERSION}
        - GIT_URL=${GIT_URL}
        - BUILD_FILE_BRANDING=${BUILD_FILE_BRANDING-}
        - DB_ENGINE=${DB_ENGINE-}
    command: /bin/bash -c docker_exec_prod_email_notifications.sh
    environment:
      - DATABASE_CONNECTION_STRING=${DATABASE_CONNECTION_STRING-}
      - HOST_ADDRESS=${HOST_ADDRESS-}
      - HOST_PORT_HTTPS=${HOST_PORT_HTTPS-}
      - SECRET_KEY=${SECRET_KEY-}
      - DEBUG=${DEBUG-}
      - ADMINS=${ADMINS-[]}
      - HEALTH_CHECK_GOVREADY_Q=${HEALTH_CHECK_GOVREADY_Q}
      - EMAIL_HOST=${EMAIL_HOST-}
      - EMAIL_PORT=${EMAIL_PORT-}
      - EMAIL_PW=${EMAIL_PW-}
      - EMAIL_DOMAIN=${EMAIL_DOMAIN-}
      - MAILGUN_API_KEY=${MAILGUN_API_KEY-}
      - BRANDING=${BRANDING-}
      - PROXY_AUTHENTICATION_USER_HEADER=${PROXY_AUTHENTICATION_USER_HEADER-}
      - PROXY_AUTHENTICATION_EMAIL_HEADER=${PROXY_AUTHENTICATION_EMAIL_HEADER-}
      - GR_PDF_GENERATOR=${GR_PDF_GENERATOR-}
      - GR_IMG_GENERATOR=${GR_IMG_GENERATOR-}
      - OKTA=${OKTA-}
    volumes:
      - ${MOUNT_FOLDER}/govready-q-email-notifications/logs:/var/log
      - ${MOUNT_FOLDER}/govready-q-email-notifications/data:/data
    depends_on:
      app:
        condition: service_healthy
    networks:
      - q_network

  nginx:
    build:
      context: ../../images/nginx
      args:
        - HOST_ADDRESS=${HOST_ADDRESS-}
        - NGINX_CERT=${BUILD_FILE_NGINX_CERT}
        - NGINX_KEY=${BUILD_FILE_NGINX_KEY}
        - APP_DOCKER_PORT=${APP_DOCKER_PORT-}
    ports:
      - "${HOST_PORT_HTTPS-443}:443"
    depends_on:
      app:
        condition: service_healthy
    networks:
      - q_network

  postgres:
    image: postgres:13.2-alpine
    ports:
      - "5432:5432"
    volumes:
      - type: volume
        source: postgres-data
        target: /postgres-data
        volume:
          nocopy: false
    environment:
      POSTGRES_DB: govready_q
      POSTGRES_PASSWORD: PASSWORD
      POSTGRES_HOST_AUTH_METHOD: trust
      PGDATA: /postgres-data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - q_network

volumes:
   postgres-data:
